version: "3.8"

services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_db_data:/data/db
  python_pipeline:
    build: .
    container_name: python_pipeline
    depends_on:
      - mongo
    links:
      - mongo
volumes:
  mongo_db_data: